name: example network
surrogate:
  epochs: 1000
  hidden_dim: 256
  lstm_hidden: 512
  output_dim: 101
  num_clusters: 100
  num_embeddings: 101
  embedding_dim: 30
  numerical_dim: 102
  weight_decay: 0.00001
  dropout: 0.2
  batch_size: 64
  learning_rate: 0.0001
  test_ratio: 0.2
  # This is the largest weight value for alpha, beta, and gamma
  largest_weight: 6
  # This is the largest cluster id, which is 100
  num_workers: 4
  # Load model? If yes, then specify the path
  load_model: True
  # Folders to save the model and the plots
  model_path: ./models/model.pt
  # Generate the data from the raw data
  generate_data: False
  # Path to the raw data to generate the data from
  raw_data_folder: /Users/ffjla/PyNetSim/tutorials/results
  # Path to the data, if it is not provided, then this folder is used to save the data
  data_folder: ./data
  plots_folder: ./plots
  print_every: 1
  plot_every: 10
